sudo: false

language: cpp

os:
  - linux

compiler:
  - gcc
  - clang

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7"; fi
- if [ "$CXX" = "clang++" ]; then export CXX="clang++-5.0" CC="clang-5.0"; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-5.0
    packages:
    - gcc-7
    - g++-7
    - clang-5.0

before_script:
  - mkdir debug
  - cd debug
  - cmake -DCMAKE_BUILD_TYPE=Debug ..

script: make
